### PR TITLE
VMO-6574 Block Connections

### PR DESCRIPTION
**Pull request by object-required**
VMO-6574-2

### CODE REVIEW

**Review by safydy-r — APPROVED** [review]
I have no much comment, I'm happy you found a way.
(I think we should split this giant component `Block.vue` in the future, it's becoming bigger and bigger)

**Comment by safydy-r** [comment]
- [ ] Fix the cursor type (use the hand icon instead of arrow) when we're hovering the exit

**Comment by safydy-r** [comment]
- [ ] fix this console when trying to drag an exit
Screen Shot 2022-08-18 at 9 22 34 AM

**Review by bulatgab — APPROVED** [review]
(This is beyond my current skills) Great work 👍

**Pull request merged**
