### PR TITLE
Vmo 690 with runner v1

### PR DESCRIPTION
**Pull request by jcbashdown**
Update: @bzabos  has done an initial review and is happy for this to move to QA.

**Notes for QA**

When testing, this `builder.config.json.txt` file can be used in the place of the default to make testing easier. Simply copy across the file and remove the `.txt` extension. It contains groups and properties and one additional languag. When copied over you can see what has changed in the diff.

[builder.config.json.txt](https://github.com/FLOIP/flow-builder/files/6421720/builder.config.json.txt)

All tests should be done for both the upload and by pasting the contents of the test files into the Paste field

- Test save and continue is disabled when the import page is in an invalid state
- Test invalid json - e.g. a file containing some random text
  - You should see an error saying you did not use valid json
- Test multiple flows - take a look at `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-multi.json`
  - You should see an error saying the importer only supports single flows
- Test lang mistmatch - `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-invalid-lang.json`
  - You should see the lang mismatches highlighted
  - You should be able to resolve by selecting from the dropdown and clicking the button
  - The language in the flow json should be appended to the languages list
  - Any resource using the old language id should be set to use the new language id
  - Edit the test of languages so that the id or other attributes no longer match the language previously matched in builder.config.json
  - You should see a loading spinner and then the edited language should be removed from the flow. Then you should see the matcher to fix the language you broke 
- Test group mismatch - `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-block-group.json`
  - You should see the group mismatches highlighted
  - You should be able to resolve by selecting from the dropdown and clicking the button
  - The groups in the flow json Core.SetGroupMembership block should be updated
  - Edit the text of groups so that the group_key no longer matches the id or the group_name no longer matches the name of the group previously matched in builder.config.json
  - You should see a loading spinner and then you should see the matcher to fix the group you broke
- Test prop mismatch -  `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-block-group.json`
  - You should see the prop mismatches highlighted
  - You should be able to resolve by selecting from the dropdown and clicking the button
  - The props in the flow json Core.SetContactProperty block should be updated
  - Edit the test of groups so that the property_key no longer matches the name of the property previously matched in builder.config.json
  - You should see a loading spinner and then you should see the matcher to fix the group you broke
- Test a valid flow `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow.json`:
  - You should see the flow rendered correctly
- Test resources work as expected - imported resources correctly associated with blocks
- Test for regressions. 
  - Focus on Create Flow in particular. 
  - Ensure that you can create a blank flow with Create Flow, then import a different flow. 
  - When you return to Home you should see both flows.
  - Test for any other regressions
- Test loop with export panel:
  - Refresh the Home page to remove all flows 
  - Create a new blank flow using the Create Flow page. Add some blocks, configure some resources
  - Copy the JSON from the export panel on the builder page
  - Return to Home and refresh to clear all flows
  - Import the copied JSON
  - The import should be valid and show exactly what you had before the refresh
- Test overwriting existing flows, resources:
  - Flows and resources are identified by the uuid field. 
  - Upload the basic flow example file - `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow.json` and view the flow in the builder. Go to Home and see the flow in the list. 
  - Edit the file to remove some blocks and resources and reupload. 
  - You should see the blocks removed in the builder and the resources removed from associated blocks (e.g. the resource removed from a message block). 
  - Return to Home - you should still see only the one flow. 
- Check validation when no props or groups in builder config
  - Remove the existing props, groups and languages from the builder config file (see the diff with the file on this branch to see where to remove things). You may need to restart `yarn serve` and refresh to load the changes.
  - Attempt the valid flow upload
  - You should see mismatches where you didn't before 
  - It should not be possible to resolve the mismatches as there are no options in the builder config.
- Test that the flow can only contain blocks in `builder.config.json`
  - `src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-unsupported-block` contains unsupported blocks, or you can edit builder.config.json to remove support for block types that are in other flows.

### CODE REVIEW

**Comment by yeboaasare** [comment]
@jcbashdown  - I get this console log when I click on the "Import the file" button

`vue.esm.js?a026:628 [Vue warn]: Error in v-on handler: “TypeError: Cannot read property ‘click’ of undefined”

found in

---> <ImportFlow> at src/views/ImportFlow.vue
       <App> at src/App.vue
         <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
invokeWithErrorHandling @ vue.esm.js?a026:1871
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7565
chooseFile @ ImportFlow.vue?322a:182
invokeWithErrorHandling @ vue.esm.js?a026:1863
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7565
vue.esm.js?a026:1897 TypeError: Cannot read property ‘click’ of undefined
    at VueComponent.chooseFile (ImportFlow.vue?322a:182)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at HTMLAnchorElement.invoker (vue.esm.js?a026:2188)
    at HTMLAnchorElement.original._wrapper (vue.esm.js?a026:7565)
    at VueComponent.chooseFile (ImportFlow.vue?322a:182)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at HTMLAnchorElement.invoker (vue.esm.js?a026:2188)
    at HTMLAnchorElement.original._wrapper (vue.esm.js?a026:7565)`

**Comment by yeboaasare** [comment]
@jcbashdown I get this error when I paste JSON directly
importHelpers.ts?90d2:59 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at checkSingleFlowOnly (importHelpers.ts?90d2:59)
    at _callee$ (import.ts?3c11:167)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
    at eval (asyncToGenerator.js?1da1:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?1da1:21)
checkSingleFlowOnly @ importHelpers.ts?90d2:59
_callee$ @ import.ts?3c11:167
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
setFlowJson @ import.ts?3c11:167
wrappedActionHandler @ vuex.esm.js?2f62:847
dispatch @ vuex.esm.js?2f62:512
boundDispatch @ vuex.esm.js?2f62:402
local.dispatch @ vuex.esm.js?2f62:775
mappedAction @ vuex.esm.js?2f62:1060
set @ ImportFlow.vue?322a:152
_callee2$ @ ImportFlow.vue?322a:164
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
handleFlowJsonTextChange @ ImportFlow.vue?322a:106
invokeFunc @ lodash.js?2ef0:10359
trailingEdge @ lodash.js?2ef0:10408
timerExpired @ lodash.js?2ef0:10396
Promise.then (async)
eval @ vuex.esm.js?2f62:515
dispatch @ vuex.esm.js?2f62:514
boundDispatch @ vuex.esm.js?2f62:402
local.dispatch @ vuex.esm.js?2f62:775
mappedAction @ vuex.esm.js?2f62:1060
set @ ImportFlow.vue?322a:152
_callee2$ @ ImportFlow.vue?322a:164
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
handleFlowJsonTextChange @ ImportFlow.vue?322a:106
invokeFunc @ lodash.js?2ef0:10359
trailingEdge @ lodash.js?2ef0:10408
timerExpired @ lodash.js?2ef0:10396
setTimeout (async)
setTimeout @ lodash.js?2ef0:6668
leadingEdge @ lodash.js?2ef0:10367
debounced @ lodash.js?2ef0:10436
setUpdatingAndHandleFlowJsonTextChange @ ImportFlow.vue?322a:157
invokeWithErrorHandling @ vue.esm.js?a026:1863
invoker @ vue.esm.js?a026:2188
invokeWithErrorHandling @ vue.esm.js?a026:1863
Vue.$emit @ vue.esm.js?a026:3897
input @ TextEditor.vue?8a98:19
invokeWithErrorHandling @ vue.esm.js?a026:1863
invoker @ vue.esm.js?a026:2188
original._wrapper @ vue.esm.js?a026:7565

**Comment by jcbashdown** [comment]
> @jcbashdown - I get this console log when I click on the "Import the file" button
> 
> `vue.esm.js?a026:628 [Vue warn]: Error in v-on handler: “TypeError: Cannot read property ‘click’ of undefined”
> 
> found in
> 
> ---> at src/views/ImportFlow.vue
> at src/App.vue
> 
> warn @ vue.esm.js?a026:628
> logError @ vue.esm.js?a026:1893
> globalHandleError @ vue.esm.js?a026:1888
> handleError @ vue.esm.js?a026:1848
> invokeWithErrorHandling @ vue.esm.js?a026:1871
> invoker @ vue.esm.js?a026:2188
> original._wrapper @ vue.esm.js?a026:7565
> chooseFile @ ImportFlow.vue?322a:182
> invokeWithErrorHandling @ vue.esm.js?a026:1863
> invoker @ vue.esm.js?a026:2188
> original._wrapper @ vue.esm.js?a026:7565
> vue.esm.js?a026:1897 TypeError: Cannot read property ‘click’ of undefined
> at VueComponent.chooseFile (ImportFlow.vue?322a:182)
> at invokeWithErrorHandling (vue.esm.js?a026:1863)
> at HTMLAnchorElement.invoker (vue.esm.js?a026:2188)
> at HTMLAnchorElement.original._wrapper (vue.esm.js?a026:7565)
> at VueComponent.chooseFile (ImportFlow.vue?322a:182)
> at invokeWithErrorHandling (vue.esm.js?a026:1863)
> at HTMLAnchorElement.invoker (vue.esm.js?a026:2188)
> at HTMLAnchorElement.original._wrapper (vue.esm.js?a026:7565)`
> 
> Screenshot 2021-05-05 at 2 46 16 PM

@yeboaasare Pushed a fix for this.

**Comment by jcbashdown** [comment]
> @jcbashdown I get this error when I paste JSON directly
> Screenshot 2021-05-05 at 2 50 32 PM
> 
> importHelpers.ts?90d2:59 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
> at checkSingleFlowOnly (importHelpers.ts?90d2:59)
> at _callee$ (import.ts?3c11:167)
> at tryCatch (runtime.js?96cf:45)
> at Generator.invoke [as _invoke] (runtime.js?96cf:274)
> at Generator.prototype. [as next] (runtime.js?96cf:97)
> at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
> at _next (asyncToGenerator.js?1da1:25)
> at eval (asyncToGenerator.js?1da1:32)
> at new Promise ()
> at eval (asyncToGenerator.js?1da1:21)
> checkSingleFlowOnly @ importHelpers.ts?90d2:59
> _callee$ @ import.ts?3c11:167
> tryCatch @ runtime.js?96cf:45
> invoke @ runtime.js?96cf:274
> prototype. @ runtime.js?96cf:97
> asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> _next @ asyncToGenerator.js?1da1:25
> eval @ asyncToGenerator.js?1da1:32
> eval @ asyncToGenerator.js?1da1:21
> setFlowJson @ import.ts?3c11:167
> wrappedActionHandler @ vuex.esm.js?2f62:847
> dispatch @ vuex.esm.js?2f62:512
> boundDispatch @ vuex.esm.js?2f62:402
> local.dispatch @ vuex.esm.js?2f62:775
> mappedAction @ vuex.esm.js?2f62:1060
> set @ ImportFlow.vue?322a:152
> _callee2$ @ ImportFlow.vue?322a:164
> tryCatch @ runtime.js?96cf:45
> invoke @ runtime.js?96cf:274
> prototype. @ runtime.js?96cf:97
> asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> _next @ asyncToGenerator.js?1da1:25
> eval @ asyncToGenerator.js?1da1:32
> eval @ asyncToGenerator.js?1da1:21
> handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> invokeFunc @ lodash.js?2ef0:10359
> trailingEdge @ lodash.js?2ef0:10408
> timerExpired @ lodash.js?2ef0:10396
> Promise.then (async)
> eval @ vuex.esm.js?2f62:515
> dispatch @ vuex.esm.js?2f62:514
> boundDispatch @ vuex.esm.js?2f62:402
> local.dispatch @ vuex.esm.js?2f62:775
> mappedAction @ vuex.esm.js?2f62:1060
> set @ ImportFlow.vue?322a:152
> _callee2$ @ ImportFlow.vue?322a:164
> tryCatch @ runtime.js?96cf:45
> invoke @ runtime.js?96cf:274
> prototype. @ runtime.js?96cf:97
> asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> _next @ asyncToGenerator.js?1da1:25
> eval @ asyncToGenerator.js?1da1:32
> eval @ asyncToGenerator.js?1da1:21
> handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> invokeFunc @ lodash.js?2ef0:10359
> trailingEdge @ lodash.js?2ef0:10408
> timerExpired @ lodash.js?2ef0:10396
> setTimeout (async)
> setTimeout @ lodash.js?2ef0:6668
> leadingEdge @ lodash.js?2ef0:10367
> debounced @ lodash.js?2ef0:10436
> setUpdatingAndHandleFlowJsonTextChange @ ImportFlow.vue?322a:157
> invokeWithErrorHandling @ vue.esm.js?a026:1863
> invoker @ vue.esm.js?a026:2188
> invokeWithErrorHandling @ vue.esm.js?a026:1863
> Vue.$emit @ vue.esm.js?a026:3897
> input @ TextEditor.vue?8a98:19
> invokeWithErrorHandling @ vue.esm.js?a026:1863
> invoker @ vue.esm.js?a026:2188
> original._wrapper @ vue.esm.js?a026:7565

@yeboaasare Can you share what you're pasting in here? I can't reproduce this.

**Comment by yeboaasare** [comment]
> > @jcbashdown I get this error when I paste JSON directly
> > Screenshot 2021-05-05 at 2 50 32 PM
> > importHelpers.ts?90d2:59 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
> > at checkSingleFlowOnly (importHelpers.ts?90d2:59)
> > at _callee$ (import.ts?3c11:167)
> > at tryCatch (runtime.js?96cf:45)
> > at Generator.invoke [as _invoke] (runtime.js?96cf:274)
> > at Generator.prototype. [as next] (runtime.js?96cf:97)
> > at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
> > at _next (asyncToGenerator.js?1da1:25)
> > at eval (asyncToGenerator.js?1da1:32)
> > at new Promise ()
> > at eval (asyncToGenerator.js?1da1:21)
> > checkSingleFlowOnly @ importHelpers.ts?90d2:59
> > _callee$ @ import.ts?3c11:167
> > tryCatch @ runtime.js?96cf:45
> > invoke @ runtime.js?96cf:274
> > prototype. @ runtime.js?96cf:97
> > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > _next @ asyncToGenerator.js?1da1:25
> > eval @ asyncToGenerator.js?1da1:32
> > eval @ asyncToGenerator.js?1da1:21
> > setFlowJson @ import.ts?3c11:167
> > wrappedActionHandler @ vuex.esm.js?2f62:847
> > dispatch @ vuex.esm.js?2f62:512
> > boundDispatch @ vuex.esm.js?2f62:402
> > local.dispatch @ vuex.esm.js?2f62:775
> > mappedAction @ vuex.esm.js?2f62:1060
> > set @ ImportFlow.vue?322a:152
> > _callee2$ @ ImportFlow.vue?322a:164
> > tryCatch @ runtime.js?96cf:45
> > invoke @ runtime.js?96cf:274
> > prototype. @ runtime.js?96cf:97
> > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > _next @ asyncToGenerator.js?1da1:25
> > eval @ asyncToGenerator.js?1da1:32
> > eval @ asyncToGenerator.js?1da1:21
> > handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> > invokeFunc @ lodash.js?2ef0:10359
> > trailingEdge @ lodash.js?2ef0:10408
> > timerExpired @ lodash.js?2ef0:10396
> > Promise.then (async)
> > eval @ vuex.esm.js?2f62:515
> > dispatch @ vuex.esm.js?2f62:514
> > boundDispatch @ vuex.esm.js?2f62:402
> > local.dispatch @ vuex.esm.js?2f62:775
> > mappedAction @ vuex.esm.js?2f62:1060
> > set @ ImportFlow.vue?322a:152
> > _callee2$ @ ImportFlow.vue?322a:164
> > tryCatch @ runtime.js?96cf:45
> > invoke @ runtime.js?96cf:274
> > prototype. @ runtime.js?96cf:97
> > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > _next @ asyncToGenerator.js?1da1:25
> > eval @ asyncToGenerator.js?1da1:32
> > eval @ asyncToGenerator.js?1da1:21
> > handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> > invokeFunc @ lodash.js?2ef0:10359
> > trailingEdge @ lodash.js?2ef0:10408
> > timerExpired @ lodash.js?2ef0:10396
> > setTimeout (async)
> > setTimeout @ lodash.js?2ef0:6668
> > leadingEdge @ lodash.js?2ef0:10367
> > debounced @ lodash.js?2ef0:10436
> > setUpdatingAndHandleFlowJsonTextChange @ ImportFlow.vue?322a:157
> > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > invoker @ vue.esm.js?a026:2188
> > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > Vue.$emit @ vue.esm.js?a026:3897
> > input @ TextEditor.vue?8a98:19
> > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > invoker @ vue.esm.js?a026:2188
> > original._wrapper @ vue.esm.js?a026:7565
> 
> @yeboaasare Can you share what you're pasting in here? I can't reproduce this.

@jcbashdown  - I pasted the content of builder.config.json

**Comment by jcbashdown** [comment]
> > > @jcbashdown I get this error when I paste JSON directly
> > > Screenshot 2021-05-05 at 2 50 32 PM
> > > importHelpers.ts?90d2:59 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
> > > at checkSingleFlowOnly (importHelpers.ts?90d2:59)
> > > at _callee$ (import.ts?3c11:167)
> > > at tryCatch (runtime.js?96cf:45)
> > > at Generator.invoke [as _invoke] (runtime.js?96cf:274)
> > > at Generator.prototype. [as next] (runtime.js?96cf:97)
> > > at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
> > > at _next (asyncToGenerator.js?1da1:25)
> > > at eval (asyncToGenerator.js?1da1:32)
> > > at new Promise ()
> > > at eval (asyncToGenerator.js?1da1:21)
> > > checkSingleFlowOnly @ importHelpers.ts?90d2:59
> > > _callee$ @ import.ts?3c11:167
> > > tryCatch @ runtime.js?96cf:45
> > > invoke @ runtime.js?96cf:274
> > > prototype. @ runtime.js?96cf:97
> > > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > > _next @ asyncToGenerator.js?1da1:25
> > > eval @ asyncToGenerator.js?1da1:32
> > > eval @ asyncToGenerator.js?1da1:21
> > > setFlowJson @ import.ts?3c11:167
> > > wrappedActionHandler @ vuex.esm.js?2f62:847
> > > dispatch @ vuex.esm.js?2f62:512
> > > boundDispatch @ vuex.esm.js?2f62:402
> > > local.dispatch @ vuex.esm.js?2f62:775
> > > mappedAction @ vuex.esm.js?2f62:1060
> > > set @ ImportFlow.vue?322a:152
> > > _callee2$ @ ImportFlow.vue?322a:164
> > > tryCatch @ runtime.js?96cf:45
> > > invoke @ runtime.js?96cf:274
> > > prototype. @ runtime.js?96cf:97
> > > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > > _next @ asyncToGenerator.js?1da1:25
> > > eval @ asyncToGenerator.js?1da1:32
> > > eval @ asyncToGenerator.js?1da1:21
> > > handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> > > invokeFunc @ lodash.js?2ef0:10359
> > > trailingEdge @ lodash.js?2ef0:10408
> > > timerExpired @ lodash.js?2ef0:10396
> > > Promise.then (async)
> > > eval @ vuex.esm.js?2f62:515
> > > dispatch @ vuex.esm.js?2f62:514
> > > boundDispatch @ vuex.esm.js?2f62:402
> > > local.dispatch @ vuex.esm.js?2f62:775
> > > mappedAction @ vuex.esm.js?2f62:1060
> > > set @ ImportFlow.vue?322a:152
> > > _callee2$ @ ImportFlow.vue?322a:164
> > > tryCatch @ runtime.js?96cf:45
> > > invoke @ runtime.js?96cf:274
> > > prototype. @ runtime.js?96cf:97
> > > asyncGeneratorStep @ asyncToGenerator.js?1da1:3
> > > _next @ asyncToGenerator.js?1da1:25
> > > eval @ asyncToGenerator.js?1da1:32
> > > eval @ asyncToGenerator.js?1da1:21
> > > handleFlowJsonTextChange @ ImportFlow.vue?322a:106
> > > invokeFunc @ lodash.js?2ef0:10359
> > > trailingEdge @ lodash.js?2ef0:10408
> > > timerExpired @ lodash.js?2ef0:10396
> > > setTimeout (async)
> > > setTimeout @ lodash.js?2ef0:6668
> > > leadingEdge @ lodash.js?2ef0:10367
> > > debounced @ lodash.js?2ef0:10436
> > > setUpdatingAndHandleFlowJsonTextChange @ ImportFlow.vue?322a:157
> > > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > > invoker @ vue.esm.js?a026:2188
> > > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > > Vue.$emit @ vue.esm.js?a026:3897
> > > input @ TextEditor.vue?8a98:19
> > > invokeWithErrorHandling @ vue.esm.js?a026:1863
> > > invoker @ vue.esm.js?a026:2188
> > > original._wrapper @ vue.esm.js?a026:7565
> > 
> > 
> > @yeboaasare Can you share what you're pasting in here? I can't reproduce this.
> 
> @jcbashdown - I pasted the content of builder.config.json

@yeboaasare Pushed a fix for this.

**Comment by yeboaasare** [comment]
@jcbashdown  - 
**What I did**
Focus on Create Flow in particular.
Ensure that you can create a blank flow with Create Flow, then import a different flow.

**Expecation**
When you return to Home you should see both flows.

**What happen**
The first flow got vanished.I only saw the imported flow

**Comment by yeboaasare** [comment]
> @jcbashdown -
> **What I did**
> Focus on Create Flow in particular.
> Ensure that you can create a blank flow with Create Flow, then import a different flow.
> 
> **Expecation**
> When you return to Home you should see both flows.
> 
> **What happened**
> The first flow got vanished.I only saw the imported flow

@jcbashdown ignore this one. I used a flow with the same uuid and that caused that issue.

**Review by yeboaasare — APPROVED** [review]

**Pull request merged**
